// C:\Users\larho\suka-smart-assistant\src\db\repositories\SessionsRepo.js
/* eslint-disable no-console */

/**
 * SessionsRepo
 * -----------------------------------------------------------------------------
 * Role in pipeline:
 *  - Imports → Intelligence → Automation → (optional) Hub export
 *  - This repo persists "sessions" generated by planners/engines (cooking,
 *    cleaning, garden, animal, preservation, storehouse). Any create/update/
 *    delete triggers eventBus emissions so the automation runtime can react
 *    (e.g., schedule runs, timers, or inventory adjustments). If familyFundMode
 *    is enabled, changes are formatted & forwarded to the Hub (best-effort).
 *
 * Core principles:
 *  - Defensive: validate inputs, normalize shapes, early-returns on errors
 *  - Consistent events: { type, ts, source, data } with ISO timestamps
 *  - Forward-thinking: domain-agnostic, extensible status & metadata
 *  - Efficient: small batch APIs, patch/upsert, and minimal allocations
 */

let db = null;
try {
  // Expect a Dexie instance with a "sessions" table.
  // Your app typically exports a configured Dexie via "@/db" or "@/db/index.js".
  const mod = require("@/db");
  db = mod?.default || mod?.db || mod;
} catch {}

let eventBus = { emit: () => {}, on: () => () => {} };
try {
  const eb = require("@/services/eventBus");
  eventBus = eb?.default || eb?.eventBus || eventBus;
} catch {}

let featureFlags = { familyFundMode: false };
try {
  featureFlags = require("@/config/featureFlags.json");
} catch {}

let HubPacketFormatter = null;
try {
  const mod = require("@/services/hub/HubPacketFormatter");
  HubPacketFormatter = mod?.default || mod;
} catch {}

let FamilyFundConnector = null;
try {
  const mod = require("@/services/hub/FamilyFundConnector");
  FamilyFundConnector = mod?.default || mod;
} catch {}

const SOURCE = "db/SessionsRepo";

/* ----------------------------------------------------------------------------
 * Utilities
 * -------------------------------------------------------------------------- */

/** ISO timestamp helper */
function isoNow() {
  return new Date().toISOString();
}

/** UUID (fallback-safe) */
function uuid() {
  try {
    // Modern browsers / Node 19+
    return globalThis?.crypto?.randomUUID?.() || null;
  } catch {}
  // Fallback
  return `sess_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

/** Stable event emitter */
function emit(type, data) {
  try {
    eventBus.emit({
      type,
      ts: isoNow(),
      source: SOURCE,
      data,
    });
  } catch (err) {
    console.warn("[SessionsRepo] event emit failed:", err);
  }
}

/**
 * Optional Hub export (silent fail). Only called for mutating operations.
 * It checks featureFlags.familyFundMode and sends a best-effort packet.
 */
async function exportToHubIfEnabled(payload) {
  if (!featureFlags?.familyFundMode || !HubPacketFormatter || !FamilyFundConnector) return;
  try {
    const packet = HubPacketFormatter.formatSessionChange?.(payload) || payload;
    await FamilyFundConnector.send?.(packet);
  } catch (err) {
    // Silent fail by design
    console.warn("[SessionsRepo] Hub export failed (silent):", err?.message || err);
  }
}

/**
 * Basic shape guard and normalization for a session record.
 * This is intentionally permissive & domain-agnostic but ensures safe defaults.
 */
function normalizeSession(input = {}) {
  if (!input || typeof input !== "object") return { ok: false, error: "Invalid session payload." };

  const now = isoNow();
  const id = input.id || uuid();

  const allowedStatuses = new Set([
    "draft",
    "scheduled",
    "in_progress",
    "completed",
    "canceled",
    "archived",
  ]);

  const record = {
    id,
    domain: String(input.domain || "").trim() || "general", // cooking, cleaning, garden, animal, preservation, storehouse
    title: String(input.title || "").trim() || "Untitled Session",
    status: allowedStatuses.has(input.status) ? input.status : "draft",
    tasks: Array.isArray(input.tasks) ? input.tasks : [], // [{id, title, duration, prerequisites, annotations, ...}]
    preferences: input.preferences && typeof input.preferences === "object" ? input.preferences : {}, // e.g., doneness, aromatics, etc.
    schedule: input.schedule && typeof input.schedule === "object" ? input.schedule : {}, // { scheduledFor, duration, recurrence }
    inventoryEffects: Array.isArray(input.inventoryEffects) ? input.inventoryEffects : [], // [{ itemId, delta, reason }]
    analytics: input.analytics && typeof input.analytics === "object" ? input.analytics : {}, // any engine hints, scoring
    metadata:
      input.metadata && typeof input.metadata === "object"
        ? input.metadata
        : {}, // arbitrary, domain-agnostic
    createdAt: input.createdAt || now,
    updatedAt: now,
    // execution-related
    executedAt: input.executedAt || null,
    canceledAt: input.canceledAt || null,
    archivedAt: input.archivedAt || null,
    // linking
    householdId: input.householdId || null,
    origin: input.origin || null, // where it came from (import url, engine name, user action)
  };

  return { ok: true, record };
}

/* ----------------------------------------------------------------------------
 * Dexie guards
 * -------------------------------------------------------------------------- */
function ensureDB() {
  if (!db || typeof db !== "object" || !db.sessions) {
    throw new Error(
      "Dexie 'db.sessions' table not available. Ensure '@/db' exports a Dexie with a 'sessions' table."
    );
  }
}

/* ----------------------------------------------------------------------------
 * Repository
 * -------------------------------------------------------------------------- */

const SessionsRepo = {
  /**
   * create(session)
   * - Inserts a new session record.
   * - Emits 'session.created' and exports to Hub (if enabled).
   */
  async create(session) {
    ensureDB();
    const res = normalizeSession(session);
    if (!res.ok) return { ok: false, error: res.error };

    const record = res.record;
    try {
      await db.sessions.put(record); // put allows upsert if id collides; we prefer explicit create, but put is idempotent
      const payload = { action: "create", session: record };
      emit("session.created", payload);
      await exportToHubIfEnabled(payload);
      return { ok: true, data: record };
    } catch (err) {
      console.error("[SessionsRepo.create] failed:", err);
      return { ok: false, error: err?.message || String(err) };
    }
  },

  /**
   * bulkCreate(list)
   * - Fast insert many. Returns {ok, data:[ids], errors:[]}
   */
  async bulkCreate(list = []) {
    ensureDB();
    if (!Array.isArray(list) || list.length === 0) {
      return { ok: false, error: "Nothing to create." };
    }
    const ready = [];
    for (const s of list) {
      const res = normalizeSession(s);
      if (res.ok) ready.push(res.record);
    }
    if (ready.length === 0) return { ok: false, error: "No valid sessions." };

    try {
      const ids = await db.sessions.bulkPut(ready); // returns last key; Dexie 4 returns array; we tolerate both
      const payload = { action: "bulkCreate", count: ready.length, sessions: ready.map(s => s.id) };
      emit("session.bulk_created", payload);
      await exportToHubIfEnabled(payload);
      return { ok: true, data: Array.isArray(ids) ? ids : ready.map(s => s.id) };
    } catch (err) {
      console.error("[SessionsRepo.bulkCreate] failed:", err);
      return { ok: false, error: err?.message || String(err) };
    }
  },

  /**
   * getById(id)
   */
  async getById(id) {
    ensureDB();
    if (!id) return { ok: false, error: "Missing id." };
    try {
      const row = await db.sessions.get(id);
      return row ? { ok: true, data: row } : { ok: false, error: "Not found." };
    } catch (err) {
      console.error("[SessionsRepo.getById] failed:", err);
      return { ok: false, error: err?.message || String(err) };
    }
  },

  /**
   * list({domain, status, from, to, limit, offset, sortBy, sortDir})
   * - Flexible query with common filters & pagination.
   */
  async list(opts = {}) {
    ensureDB();
    const {
      domain = null,
      status = null,
      from = null, // ISO createdAt lower-bound
      to = null, // ISO createdAt upper-bound
      limit = 100,
      offset = 0,
      sortBy = "createdAt",
      sortDir = "desc", // 'asc' | 'desc'
    } = opts;

    try {
      let coll = db.sessions.toCollection();

      if (domain) {
        coll = coll.and(s => s.domain === domain);
      }
      if (status) {
        // allow array or string
        const statuses = Array.isArray(status) ? new Set(status) : new Set([status]);
        coll = coll.and(s => statuses.has(s.status));
      }
      if (from) {
        coll = coll.and(s => (s.createdAt || "") >= from);
      }
      if (to) {
        coll = coll.and(s => (s.createdAt || "") < to);
      }

      // Sorting
      const dir = sortDir === "asc" ? 1 : -1;
      const items = await coll.sortBy(sortBy).then(arr => (dir === 1 ? arr : arr.reverse()));

      // Pagination
      const slice = items.slice(offset, offset + limit);
      return {
        ok: true,
        data: {
          total: items.length,
          items: slice,
          offset,
          limit,
        },
      };
    } catch (err) {
      console.error("[SessionsRepo.list] failed:", err);
      return { ok: false, error: err?.message || String(err) };
    }
  },

  /**
   * update(id, next)
   * - Replaces the session with normalized next data (keeping id).
   * - Emits 'session.updated' and hub export.
   */
  async update(id, next) {
    ensureDB();
    if (!id || !next || typeof next !== "object") {
      return { ok: false, error: "Invalid update payload." };
    }
    const current = await db.sessions.get(id);
    if (!current) return { ok: false, error: "Not found." };

    const res = normalizeSession({ ...next, id, createdAt: current.createdAt });
    if (!res.ok) return { ok: false, error: res.error };

    try {
      await db.sessions.put(res.record);
      const payload = { action: "update", session: res.record };
      emit("session.updated", payload);
      await exportToHubIfEnabled(payload);
      return { ok: true, data: res.record };
    } catch (err) {
      console.error("[SessionsRepo.update] failed:", err);
      return { ok: false, error: err?.message || String(err) };
    }
  },

  /**
   * patch(id, partial)
   * - Shallow merge updates (safer, keeps unknown fields intact).
   */
  async patch(id, partial = {}) {
    ensureDB();
    if (!id || typeof partial !== "object") {
      return { ok: false, error: "Invalid patch payload." };
    }
    try {
      const current = await db.sessions.get(id);
      if (!current) return { ok: false, error: "Not found." };

      const merged = { ...current, ...partial, id, updatedAt: isoNow() };
      await db.sessions.put(merged);

      const payload = { action: "patch", session: merged, fields: Object.keys(partial) };
      emit("session.patched", payload);
      await exportToHubIfEnabled(payload);
      return { ok: true, data: merged };
    } catch (err) {
      console.error("[SessionsRepo.patch] failed:", err);
      return { ok: false, error: err?.message || String(err) };
    }
  },

  /**
   * upsert(session)
   * - If id exists, patch; otherwise, create.
   */
  async upsert(session = {}) {
    ensureDB();
    const id = session?.id;
    if (!id) {
      return this.create(session);
    }
    const existing = await db.sessions.get(id);
    return existing ? this.patch(id, session) : this.create(session);
  },

  /**
   * remove(id)
   * - Deletes the session. Emits 'session.deleted' & hub export.
   */
  async remove(id) {
    ensureDB();
    if (!id) return { ok: false, error: "Missing id." };
    try {
      const current = await db.sessions.get(id);
      if (!current) return { ok: false, error: "Not found." };

      await db.sessions.delete(id);
      const payload = { action: "delete", id, session: current };
      emit("session.deleted", payload);
      await exportToHubIfEnabled(payload);
      return { ok: true, data: { id } };
    } catch (err) {
      console.error("[SessionsRepo.remove] failed:", err);
      return { ok: false, error: err?.message || String(err) };
    }
  },

  /**
   * bulkRemove(ids[])
   */
  async bulkRemove(ids = []) {
    ensureDB();
    if (!Array.isArray(ids) || ids.length === 0) return { ok: false, error: "Nothing to remove." };
    try {
      await db.sessions.bulkDelete(ids);
      const payload = { action: "bulkDelete", ids };
      emit("session.bulk_deleted", payload);
      await exportToHubIfEnabled(payload);
      return { ok: true, data: ids };
    } catch (err) {
      console.error("[SessionsRepo.bulkRemove] failed:", err);
      return { ok: false, error: err?.message || String(err) };
    }
  },

  /* --------------------------------------------------------------------------
   * Convenience status transitions — standardized automation hooks
   * ------------------------------------------------------------------------ */

  async markScheduled(id, scheduledForISO) {
    return this.patch(id, {
      status: "scheduled",
      schedule: { ...(await db.sessions.get(id)).schedule, scheduledFor: scheduledForISO },
    }).then((res) => {
      if (res.ok) {
        const payload = { action: "status.scheduled", id, scheduledFor: scheduledForISO };
        emit("session.scheduled", payload);
        exportToHubIfEnabled(payload);
      }
      return res;
    });
  },

  async start(id) {
    return this.patch(id, { status: "in_progress" }).then((res) => {
      if (res.ok) {
        const payload = { action: "status.started", id };
        emit("session.started", payload);
        exportToHubIfEnabled(payload);
      }
      return res;
    });
  },

  async markExecuted(id, executedAtISO = isoNow()) {
    return this.patch(id, { status: "completed", executedAt: executedAtISO }).then((res) => {
      if (res.ok) {
        // Note: Downstream may also emit domain-specific events (e.g., meal.executed)
        const payload = { action: "status.completed", id, executedAt: executedAtISO };
        emit("session.completed", payload);
        exportToHubIfEnabled(payload);
      }
      return res;
    });
  },

  async cancel(id, reason = null) {
    return this.patch(id, { status: "canceled", canceledAt: isoNow(), metadata: { reason } }).then(
      (res) => {
        if (res.ok) {
          const payload = { action: "status.canceled", id, reason };
          emit("session.canceled", payload);
          exportToHubIfEnabled(payload);
        }
        return res;
      }
    );
  },

  async archive(id) {
    return this.patch(id, { status: "archived", archivedAt: isoNow() }).then((res) => {
      if (res.ok) {
        const payload = { action: "status.archived", id };
        emit("session.archived", payload);
        exportToHubIfEnabled(payload);
      }
      return res;
    });
  },

  /* --------------------------------------------------------------------------
   * Finders / helpers
   * ------------------------------------------------------------------------ */

  async byStatus(status, limit = 100) {
    return this.list({ status, limit });
  },

  async upcoming(limit = 50) {
    ensureDB();
    try {
      const now = isoNow();
      const coll = db.sessions
        .toCollection()
        .and(
          (s) =>
            (s.status === "scheduled" || s.status === "in_progress") &&
            s?.schedule?.scheduledFor &&
            s.schedule.scheduledFor >= now
        );

      const arr = await coll.sortBy("schedule.scheduledFor");
      return { ok: true, data: arr.slice(0, limit) };
    } catch (err) {
      console.error("[SessionsRepo.upcoming] failed:", err);
      return { ok: false, error: err?.message || String(err) };
    }
  },

  async recent(limit = 50) {
    ensureDB();
    try {
      const arr = await db.sessions.toCollection().reverse().sortBy("updatedAt");
      return { ok: true, data: arr.slice(0, limit) };
    } catch (err) {
      console.error("[SessionsRepo.recent] failed:", err);
      return { ok: false, error: err?.message || String(err) };
    }
  },
};

export default SessionsRepo;
