// Bridge re-export for Vite build compatibility.
// Auto-generated by tools/scripts/generate-view-bridges.mjs
// DO NOT EDIT by hand (edit the underlying view instead).

// Supports imports like:
//   "@/features/calculators/health/BMICalculator.view"
//
// Actual implementation lives at:
//   "./BMICalculator/BMICalculator.view.jsx"

export { default } from "./BMICalculator/BMICalculator.view.jsx";
