// Bridge re-export for Vite build compatibility.
// Auto-generated by tools/scripts/generate-view-bridges.mjs
// DO NOT EDIT by hand (edit the underlying view instead).

// Supports imports like:
//   "@/features/calculators/health/MicronutrientCalculator.view"
//
// Actual implementation lives at:
//   "./MicronutrientCalculator/MicronutrientCalculator.view.jsx"

export { default } from "./MicronutrientCalculator/MicronutrientCalculator.view.jsx";
