// src/ai/automation/events.js
// Canonical household event names used across agents and UI

export const EVENTS = {
  // Calendar & sessions
  SESSION: {
    PLANNED: {
      COOKING: "SESSION.PLANNED.COOKING",
      CLEANING: "SESSION.PLANNED.CLEANING",
      GARDENING: "SESSION.PLANNED.GARDENING",
    },
    STARTED: {
      COOKING: "SESSION.STARTED.COOKING",
      CLEANING: "SESSION.STARTED.CLEANING",
      GARDENING: "SESSION.STARTED.GARDENING",
    },
    FINISHED: {
      COOKING: "SESSION.FINISHED.COOKING",
      CLEANING: "SESSION.FINISHED.CLEANING",
      GARDENING: "SESSION.FINISHED.GARDENING",
    },
  },

  // Inventory & food
  INVENTORY: {
    SURPLUS: "INVENTORY.SURPLUS.DETECTED",
    LOW: "INVENTORY.LOW.DETECTED",
    RESERVED: "INVENTORY.RESERVED",
    DEDUCTED: "INVENTORY.DEDUCTED",
  },

  // Garden & season
  GARDEN: {
    HARVEST_WINDOW: "GARDEN.HARVEST.WINDOW",
    PLANTING_WINDOW: "GARDEN.PLANTING.WINDOW",
    PEST_RISK: "GARDEN.PEST.RISK",
  },
  WEATHER: {
    FROST_ALERT: "WEATHER.FROST.ALERT",
    HEAT_ALERT: "WEATHER.HEAT.ALERT",
    RAIN_WINDOW: "WEATHER.RAIN.WINDOW",
  },

  // Rhythm
  DAY: { MORNING: "DAY.MORNING", AFTERNOON: "DAY.AFTERNOON", EVENING: "DAY.EVENING" },
  SABBATH: { PREP: "SABBATH.PREP.WINDOW", START: "SABBATH.START", END: "SABBATH.END" },
};

export default EVENTS;
