// Bridge re-export for Vite build compatibility.
// Auto-generated by tools/scripts/generate-view-bridges.mjs
// DO NOT EDIT by hand (edit the underlying view instead).

// Supports imports like:
//   "@/features/calculators/stability/HouseholdStabilityCalculator.view"
//
// Actual implementation lives at:
//   "./HouseholdStabilityCalculator/HouseholdStabilityCalculator.view.jsx"

export { default } from "./HouseholdStabilityCalculator/HouseholdStabilityCalculator.view.jsx";
