// Bridge re-export for Vite build compatibility.
// Auto-generated by tools/scripts/generate-view-bridges.mjs
// DO NOT EDIT by hand (edit the underlying view instead).

// Supports imports like:
//   "@/features/calculators/calendar/FeastDayAlignmentCalculator.view"
//
// Actual implementation lives at:
//   "./FeastDayAlignmentCalculator/FeastDayAlignmentCalculator.view.jsx"

export { default } from "./FeastDayAlignmentCalculator/FeastDayAlignmentCalculator.view.jsx";
