// Bridge re-export for Vite build compatibility.
// Auto-generated by tools/scripts/generate-view-bridges.mjs
// DO NOT EDIT by hand (edit the underlying view instead).

// Supports imports like:
//   "@/features/calculators/calendar/HebrewMonthStartCalendar.view"
//
// Actual implementation lives at:
//   "./HebrewMonthStartCalendar/HebrewMonthStartCalendar.view.jsx"

export { default } from "./HebrewMonthStartCalendar/HebrewMonthStartCalendar.view.jsx";
