"use strict";

const HOUSEHOLD_ROLES = Object.freeze({
  OWNER: "owner",
  ADMIN: "admin",
  MEMBER: "member",
  GUEST: "guest",
});

const PLANNER_ADMIN_ROLES = Object.freeze([
  HOUSEHOLD_ROLES.OWNER,
  HOUSEHOLD_ROLES.ADMIN,
]);

const WORKFLOW_STATES = Object.freeze({
  DRAFT: "draft",
  PENDING_APPROVAL: "pending_approval",
  ACTIVE: "active",
  BLOCKED: "blocked",
  COMPLETED: "completed",
  ARCHIVED: "archived",
});

const COLLABORATION_ACTIONS = Object.freeze({
  ASSIGNMENT_CREATED: "assignment.created",
  TASK_COMPLETED: "task.completed",
  FEED_POSTED: "feed.posted",
  FEED_COMMENTED: "feed.commented",
  FEED_MENTIONED: "feed.mentioned",
  APPROVAL_REQUESTED: "approval.requested",
  APPROVAL_DECIDED: "approval.decided",
  OVERDUE_ALERTED: "overdue.alerted",
  COMMUNITY_INVITED: "community.invited",
});

const NOTIFICATION_EVENT_SEVERITY = Object.freeze({
  CRITICAL: "critical",
  ACTION_REQUIRED: "action_required",
  INFORMATIONAL: "informational",
});

const NOTIFICATION_EVENT_TYPES = Object.freeze({
  ASSIGNMENT_CREATED: {
    key: COLLABORATION_ACTIONS.ASSIGNMENT_CREATED,
    severity: NOTIFICATION_EVENT_SEVERITY.ACTION_REQUIRED,
  },
  TASK_COMPLETED: {
    key: COLLABORATION_ACTIONS.TASK_COMPLETED,
    severity: NOTIFICATION_EVENT_SEVERITY.INFORMATIONAL,
  },
  FEED_MENTIONED: {
    key: COLLABORATION_ACTIONS.FEED_MENTIONED,
    severity: NOTIFICATION_EVENT_SEVERITY.ACTION_REQUIRED,
  },
  APPROVAL_REQUESTED: {
    key: COLLABORATION_ACTIONS.APPROVAL_REQUESTED,
    severity: NOTIFICATION_EVENT_SEVERITY.ACTION_REQUIRED,
  },
  APPROVAL_DECIDED: {
    key: COLLABORATION_ACTIONS.APPROVAL_DECIDED,
    severity: NOTIFICATION_EVENT_SEVERITY.INFORMATIONAL,
  },
  OVERDUE_ALERTED: {
    key: COLLABORATION_ACTIONS.OVERDUE_ALERTED,
    severity: NOTIFICATION_EVENT_SEVERITY.CRITICAL,
  },
  COMMUNITY_INVITED: {
    key: COLLABORATION_ACTIONS.COMMUNITY_INVITED,
    severity: NOTIFICATION_EVENT_SEVERITY.INFORMATIONAL,
  },
});

module.exports = {
  HOUSEHOLD_ROLES,
  PLANNER_ADMIN_ROLES,
  WORKFLOW_STATES,
  COLLABORATION_ACTIONS,
  NOTIFICATION_EVENT_SEVERITY,
  NOTIFICATION_EVENT_TYPES,
};
